name:                hybridsys-security-typechecker
version:             0.1.0.0
github:              "gautammohan/hybridsys-security-typechecker"
license:             BSD3
author:              "Gautam Mohan"
maintainer:          "s.gautam.mohan@gmail.com"
copyright:           "2019 Gautam Mohan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gautammohan/hybrid-sectypes#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 1
- mtl >= 2.2.2 && < 3
- aeson >= 1.4.2 && < 1.5
- utf8-string >= 1.0.1 && < 1.1
- parsec >= 3.1.13 && < 3.2
- bytestring >= 0.10.8 && < 0.11
- split >= 0.2.3 && < 0.3
- text >= 1.2.3 && < 1.3
- hspec >= 2.6.1 && < 2.7
- HUnit >= 1.6.0 && < 1.7
- process >= 1.6.3 && < 1.7
- fgl >= 5.7.0 && < 5.8

library:
  source-dirs: src

executables:
  hybridsys-security-typechecker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hybridsys-security-typechecker

tests:
  hybridsys-security-typechecker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hybridsys-security-typechecker
